// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateLobby(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLobby'](arg1, arg2, arg3);
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetLobbies() {
  return window['go']['main']['App']['GetLobbies']();
}

export function GetLobby(arg1) {
  return window['go']['main']['App']['GetLobby'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function JoinLobby(arg1) {
  return window['go']['main']['App']['JoinLobby'](arg1);
}

export function LeaveLobby(arg1) {
  return window['go']['main']['App']['LeaveLobby'](arg1);
}

export function SelectInterface(arg1) {
  return window['go']['main']['App']['SelectInterface'](arg1);
}

export function SendChat(arg1, arg2) {
  return window['go']['main']['App']['SendChat'](arg1, arg2);
}

export function StartTunnel(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartTunnel'](arg1, arg2, arg3, arg4, arg5, arg6);
}
