// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPermissions() {
  return window['go']['main']['App']['CheckPermissions']();
}

export function CreateLobby(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLobby'](arg1, arg2, arg3);
}

export function CreateLobbyWithMode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateLobbyWithMode'](arg1, arg2, arg3, arg4, arg5);
}

export function DetectPublicIP() {
  return window['go']['main']['App']['DetectPublicIP']();
}

export function GetGamertag() {
  return window['go']['main']['App']['GetGamertag']();
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetLobbies() {
  return window['go']['main']['App']['GetLobbies']();
}

export function GetLobby(arg1) {
  return window['go']['main']['App']['GetLobby'](arg1);
}

export function GetServerPing() {
  return window['go']['main']['App']['GetServerPing']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function JoinLobby(arg1) {
  return window['go']['main']['App']['JoinLobby'](arg1);
}

export function JoinLobbyByCode(arg1) {
  return window['go']['main']['App']['JoinLobbyByCode'](arg1);
}

export function LeaveLobby(arg1) {
  return window['go']['main']['App']['LeaveLobby'](arg1);
}

export function RefreshLobby() {
  return window['go']['main']['App']['RefreshLobby']();
}

export function RequestPermissions() {
  return window['go']['main']['App']['RequestPermissions']();
}

export function SelectInterface(arg1) {
  return window['go']['main']['App']['SelectInterface'](arg1);
}

export function SetGamertag(arg1) {
  return window['go']['main']['App']['SetGamertag'](arg1);
}

export function StartTunnel(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartTunnel'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TryUPnP(arg1) {
  return window['go']['main']['App']['TryUPnP'](arg1);
}
