// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckPermissions():Promise<main.PermissionStatus>;

export function CreateLobby(arg1:string,arg2:string,arg3:number):Promise<main.LobbyInfo>;

export function GetGamertag():Promise<string>;

export function GetInterfaces():Promise<Array<main.NetworkInterface>>;

export function GetLobbies():Promise<Array<main.LobbyInfo>>;

export function GetLobby(arg1:string):Promise<main.LobbyInfo>;

export function GetServerPing():Promise<number>;

export function GetStatus():Promise<main.AppStatus>;

export function JoinLobby(arg1:string):Promise<main.LobbyInfo>;

export function JoinLobbyByCode(arg1:string):Promise<main.LobbyInfo>;

export function LeaveLobby(arg1:string):Promise<void>;

export function RefreshLobby():Promise<main.LobbyInfo>;

export function RequestPermissions():Promise<void>;

export function SelectInterface(arg1:string):Promise<void>;

export function SetGamertag(arg1:string):Promise<void>;

export function StartTunnel(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;
