// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateLobby(arg1:string,arg2:string,arg3:number):Promise<main.LobbyInfo>;

export function GetInterfaces():Promise<Array<main.NetworkInterface>>;

export function GetLobbies():Promise<Array<main.LobbyInfo>>;

export function GetLobby(arg1:string):Promise<main.LobbyInfo>;

export function GetStatus():Promise<main.AppStatus>;

export function JoinLobby(arg1:string):Promise<main.LobbyInfo>;

export function LeaveLobby(arg1:string):Promise<void>;

export function SelectInterface(arg1:string):Promise<void>;

export function SendChat(arg1:string,arg2:string):Promise<void>;
